# Generated by Django 2.2.5 on 2019-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20190916_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='text',
        ),
        migrations.AddField(
            model_name='index',
            name='name',
            field=models.CharField(default='IndexName', help_text='Enter field documentation', max_length=100),
        ),
    ]
