# Generated by Django 2.2.5 on 2019-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20190916_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dname_Indexname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter index name', max_length=100, unique=True)),
                ('data_one', models.IntegerField(default=0)),
                ('data_two', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
