# Generated by Django 2.2.5 on 2019-09-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_auto_20190916_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dname_indexname',
            name='calculated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
