# Generated by Django 2.2.5 on 2019-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_dname_indexname_calculated_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dname_indexname',
            name='calculated_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
