# Generated by Django 2.2.5 on 2019-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_auto_20190916_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dname_indexname',
            name='name',
            field=models.CharField(help_text='Enter index name', max_length=100),
        ),
    ]
