# Generated by Django 2.2.5 on 2019-09-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_auto_20190916_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dname_indexname',
            name='calculated_value',
        ),
    ]
