# Generated by Django 2.2.5 on 2019-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_auto_20190916_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dname_indexname',
            name='data_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dname_indexname',
            name='data_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
