# Generated by Django 2.2.5 on 2019-09-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_auto_20190916_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(help_text='Enter department name', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='dname_indexname',
            old_name='name',
            new_name='index_name',
        ),
        migrations.AddField(
            model_name='dname_indexname',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ims.Department'),
        ),
    ]
