# Generated by Django 2.2.5 on 2019-09-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0016_auto_20190917_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dname_Indexname',
            new_name='Index',
        ),
    ]
