# Generated by Django 2.2.5 on 2019-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0017_auto_20190917_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='index_name',
            new_name='name',
        ),
    ]
