# Generated by Django 2.2.5 on 2019-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0018_auto_20190917_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='calculated_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
