# Generated by Django 2.2.5 on 2019-09-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0019_auto_20190917_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='ims.Department'),
        ),
    ]
