# Generated by Django 2.2.5 on 2019-09-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0021_auto_20190917_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Department'),
        ),
    ]
