# Generated by Django 2.2.5 on 2019-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0022_auto_20190917_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='calculated_value',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
