# Generated by Django 2.2.5 on 2019-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0023_auto_20190917_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='data_two',
            field=models.IntegerField(),
        ),
    ]
