# Generated by Django 2.2.5 on 2019-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0024_auto_20190917_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='data_two',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
