# Generated by Django 2.2.5 on 2019-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0025_auto_20190917_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='calculated_value',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
